# Generated by Django 4.2 on 2025-04-06 12:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chapter", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="chapter",
            table="course_chapter",
        ),
        migrations.AlterModelTable(
            name="chaptertranslation",
            table="course_chapter_translation",
        ),
    ]
