version: "3.9"

services:
  backend:
    hostname: backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile.local
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./backend/:/usr/src/app/backend
      - staticfiles:/usr/src/app/backend/static
      - mediafiles:/usr/src/app/backend/media
    environment:
      - LOCAL=${LOCAL}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOST=${ALLOWED_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - CONTACT_EMAIL=${CONTACT_EMAIL}
      - NOREPLY_EMAIL=${NOREPLY_EMAIL}
      - GOOGLE_CREDENTIALS=${GOOGLE_CREDENTIALS}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - DUMMY_STUDENT_EMAIL=${DUMMY_STUDENT_EMAIL}
      - DUMMY_STUDENT_PASSWORD=${DUMMY_STUDENT_PASSWORD}
      - BASE_FRONTEND_URL=${BASE_URL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - FACEBOOK_CLIENT_ID=${FACEBOOK_CLIENT_ID}
      - FACEBOOK_CLIENT_SECRET=${FACEBOOK_CLIENT_SECRET}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
    depends_on:
      - db
      - redis

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile.local
      target: dev
    restart: always
    command: yarn dev
    environment:
      - WATCHPACK_POLLING=true
      - NEXT_PUBLIC_ENV=LOCAL
      - NEXT_PUBLIC_BASE_URL=${BASE_URL}
      - NEXT_PUBLIC_API_URL=${API_URL}
      - NEXT_PUBLIC_GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - NEXT_PUBLIC_FACEBOOK_CLIENT_ID=${FACEBOOK_CLIENT_ID}
      - NEXT_PUBLIC_GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
    volumes:
      - ./frontend:/usr/src/app/frontend
      - /usr/src/app/frontend/node_modules
      - /usr/src/app/frontend/.next

  nginx:
    container_name: nginx
    image: nginx:latest
    build:
      context: ./nginx
    ports:
      - 80:80
    volumes:
      - staticfiles:/usr/src/app/backend/static
      - mediafiles:/usr/src/app/backend/media
    depends_on:
      - backend
      - frontend

  redis:
    container_name: redis
    image: redis:7.2.5-bookworm
    restart: always
    volumes:
      - "redis:/data"

  db:
    container_name: database
    image: postgres:15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

volumes:
  postgres_data:
  redis:
  staticfiles:
  mediafiles:
