version: "3.9"

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile.local
      target: dev
    restart: always
    command: yarn dev
    environment:
      - WATCHPACK_POLLING=true
      - NEXT_PUBLIC_ENV=LOCAL
      - NEXT_PUBLIC_BASE_URL=${BASE_URL}
      - NEXT_PUBLIC_API_URL=${API_URL}
      - NEXT_PUBLIC_GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - NEXT_PUBLIC_FACEBOOK_CLIENT_ID=${FACEBOOK_CLIENT_ID}
    volumes:
      - ./frontend:/usr/src/app/frontend
      - /usr/src/app/frontend/node_modules
      - /usr/src/app/frontend/.next

  nginx:
    container_name: nginx
    image: nginx:latest
    build:
      context: ./nginx
    ports:
      - 80:80
    depends_on:
      - frontend
