# Generated by Django 4.2 on 2025-04-06 16:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("topic", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="topic",
            options={"verbose_name_plural": "Topics"},
        ),
    ]
