# Generated by Django 4.2 on 2025-04-03 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chapter', '0001_initial'),
        ('category', '0001_initial'),
        ('technology', '0001_initial'),
        ('level', '0001_initial'),
        ('instructor_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(unique=True)),
                ('duration', models.PositiveIntegerField()),
                ('chat_url', models.URLField()),
                ('active', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='category.category')),
                ('chapters', models.ManyToManyField(related_name='courses', to='chapter.chapter')),
                ('instructors', models.ManyToManyField(related_name='courses', to='instructor_user.instructor')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='level.level')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='technology.technology')),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='CourseTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('language', models.CharField(choices=[('en', 'En'), ('pl', 'Pl')], max_length=2)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('overview', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='course.course')),
            ],
            options={
                'verbose_name_plural': 'Course translations',
                'db_table': 'course_translation',
                'unique_together': {('course', 'language')},
            },
        ),
    ]
