# Generated by Django 4.2 on 2025-03-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_level', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courselevel',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='courselevel',
            table='course_level',
        ),
        migrations.AlterModelTable(
            name='courseleveltranslation',
            table='course_level_translation',
        ),
    ]
