name: Frontend Linting Workflow

on:
  workflow_call:

jobs:
  lint-frontend:
    name: Lint Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          cd frontend
          npm install --legacy-peer-deps

      - name: Run linting
        run: |
          npm run fm:check
          npm run lint:check
