name: Broker Testing Workflow

on:
  workflow_call:

jobs:
  test-broker:
    name: Test Broker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          cd broker
          npm install

      - name: Run tests
        run: |
          npm run test:coverage
