# Generated by Django 4.2 on 2025-05-17 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('technology', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_name', models.CharField(blank=True, null=True)),
                ('starter_code', models.TextField()),
                ('solution_code', models.TextField()),
                ('penalty_points', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Coding lessons',
                'db_table': 'course_coding_lesson',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(unique=True)),
                ('points', models.PositiveIntegerField(default=0)),
                ('type', models.CharField(choices=[('reading', 'Reading'), ('video', 'Video'), ('quiz', 'Quiz'), ('coding', 'Coding')], max_length=7)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Lessons',
                'db_table': 'course_lesson',
            },
        ),
        migrations.CreateModel(
            name='QuizLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quiz_type', models.CharField(choices=[('single', 'Single'), ('multi', 'Multi')], max_length=6)),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='lesson.lesson')),
            ],
            options={
                'verbose_name_plural': 'Quiz lessons',
                'db_table': 'course_quiz_lesson',
            },
        ),
        migrations.CreateModel(
            name='QuizLessonTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('language', models.CharField(choices=[('en', 'En'), ('pl', 'Pl')], max_length=2)),
                ('name', models.CharField(max_length=255)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='lesson.quizlesson')),
            ],
            options={
                'verbose_name_plural': 'Quiz lesson translations',
                'db_table': 'course_quiz_lesson_translation',
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('translation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='lesson.quizlessontranslation')),
            ],
            options={
                'verbose_name_plural': 'Quiz questions',
                'db_table': 'course_quiz_question',
            },
        ),
        migrations.CreateModel(
            name='ReadingLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reading', to='lesson.lesson')),
            ],
            options={
                'verbose_name_plural': 'Reading lessons',
                'db_table': 'course_reading_lesson',
            },
        ),
        migrations.CreateModel(
            name='VideoLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video_url', models.URLField()),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='lesson.lesson')),
            ],
            options={
                'verbose_name_plural': 'Video lessons',
                'db_table': 'course_video_lesson',
            },
        ),
        migrations.CreateModel(
            name='VideoLessonTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('language', models.CharField(choices=[('en', 'En'), ('pl', 'Pl')], max_length=2)),
                ('name', models.CharField(max_length=255)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='lesson.videolesson')),
            ],
            options={
                'verbose_name_plural': 'Video lesson translations',
                'db_table': 'course_video_lesson_translation',
            },
        ),
        migrations.CreateModel(
            name='ReadingLessonTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('language', models.CharField(choices=[('en', 'En'), ('pl', 'Pl')], max_length=2)),
                ('name', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='lesson.readinglesson')),
            ],
            options={
                'verbose_name_plural': 'Reading lesson translations',
                'db_table': 'course_reading_lesson_translation',
            },
        ),
        migrations.CreateModel(
            name='QuizQuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='lesson.quizquestion')),
            ],
            options={
                'verbose_name_plural': 'Quiz question options',
                'db_table': 'course_quiz_question_option',
            },
        ),
        migrations.CreateModel(
            name='CodingLessonTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('language', models.CharField(choices=[('en', 'En'), ('pl', 'Pl')], max_length=2)),
                ('name', models.CharField(max_length=255)),
                ('introduction', models.TextField()),
                ('instructions', models.TextField()),
                ('hint', models.TextField(blank=True, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='lesson.codinglesson')),
            ],
            options={
                'verbose_name_plural': 'Coding lesson translations',
                'db_table': 'course_coding_lesson_translation',
            },
        ),
        migrations.AddField(
            model_name='codinglesson',
            name='lesson',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coding', to='lesson.lesson'),
        ),
        migrations.AddField(
            model_name='codinglesson',
            name='technology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='technology.technology'),
        ),
    ]
