# Generated by Django 4.2 on 2025-04-06 12:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lesson", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="codinglesson",
            table="course_coding_lesson",
        ),
        migrations.AlterModelTable(
            name="codinglessontranslation",
            table="course_coding_lesson_translation",
        ),
        migrations.AlterModelTable(
            name="lesson",
            table="course_lesson",
        ),
        migrations.AlterModelTable(
            name="quizlesson",
            table="course_quiz_lesson",
        ),
        migrations.AlterModelTable(
            name="quizlessontranslation",
            table="course_quiz_lesson_translation",
        ),
        migrations.AlterModelTable(
            name="readinglesson",
            table="course_reading_lesson",
        ),
        migrations.AlterModelTable(
            name="readinglessontranslation",
            table="course_reading_lesson_translation",
        ),
        migrations.AlterModelTable(
            name="videolesson",
            table="course_video_lesson",
        ),
        migrations.AlterModelTable(
            name="videolessontranslation",
            table="course_video_lesson_translation",
        ),
    ]
