# Generated by Django 4.2 on 2025-04-17 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("lesson", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuizQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("text", models.TextField()),
            ],
            options={
                "verbose_name_plural": "Quiz questions",
                "db_table": "course_quiz_question",
            },
        ),
        migrations.RemoveField(
            model_name="quizlessontranslation",
            name="questions",
        ),
        migrations.CreateModel(
            name="QuizQuestionOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("text", models.CharField(max_length=255)),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="lesson.quizquestion",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Quiz question options",
                "db_table": "course_quiz_question_option",
            },
        ),
        migrations.AddField(
            model_name="quizquestion",
            name="translation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="lesson.quizlessontranslation",
            ),
        ),
    ]
