# Generated by Django 4.2 on 2025-04-17 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("lesson", "0002_quizquestion_remove_quizlessontranslation_questions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizquestion",
            name="translation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="question",
                to="lesson.quizlessontranslation",
            ),
        ),
    ]
