# Generated by Django 4.2 on 2025-04-27 07:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lesson", "0003_alter_quizquestion_translation"),
    ]

    operations = [
        migrations.AddField(
            model_name="codinglesson",
            name="file_name",
            field=models.CharField(blank=True, null=True),
        ),
    ]
