name: Detect Changes Workflow

on:
  workflow_call:
    secrets:
      token:
        required: true
    outputs:
      backend:
        description: "Changes in backend"
        value: ${{ jobs.detect-changes.outputs.backend }}
      frontend:
        description: "Changes in frontend"
        value: ${{ jobs.detect-changes.outputs.frontend }}
      broker:
        description: "Changes in broker"
        value: ${{ jobs.detect-changes.outputs.broker }}
      sandbox-python:
        description: "Changes in sandbox-python"
        value: ${{ jobs.detect-changes.outputs.sandbox-python }}

jobs:
  detect-changes:
    name: Detect Changes
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
      broker: ${{ steps.filter.outputs.broker }}
      sandbox-python: ${{ steps.filter.outputs.sandbox-python }}
    steps:
      - name: Detect changes using paths-filter
        uses: dorny/paths-filter@v3
        id: filter
        with:
          token: ${{ secrets.token }}
          filters: |
            backend:
              - 'backend/**'
            frontend:
              - 'frontend/**'
            broker:
              - 'broker/**'
            sandbox-python:
              - 'sandbox/python/**'
