# Generated by Django 4.2 on 2025-04-06 12:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("technology", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="technology",
            table="course_technology",
        ),
    ]
