# Generated by Django 4.2 on 2025-04-14 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("student_user", "0001_initial"),
        ("subscription", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plansubscription",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to="student_user.student",
            ),
        ),
    ]
