# Generated by Django 4.2 on 2025-03-26 18:27

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_create_superuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=user.models.user_directory_path,
            ),
        ),
    ]
