# Generated by Django 4.2 on 2025-03-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_alter_user_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="join_type",
            field=models.CharField(
                choices=[
                    ("email", "Email"),
                    ("google", "Google"),
                    ("facebook", "Facebook"),
                    ("github", "Github"),
                ],
                default="email",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("instructor", "Instructor"),
                    ("student", "Student"),
                ],
                default="student",
                max_length=10,
            ),
        ),
    ]
