# Generated by Django 4.2 on 2025-04-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_blog_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="visits",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
