# Generated by Django 4.2 on 2025-04-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("progress", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseprogress",
            name="answer",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
