# Generated by Django 4.2 on 2025-04-06 12:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("level", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="level",
            table="course_level",
        ),
        migrations.AlterModelTable(
            name="leveltranslation",
            table="course_level_translation",
        ),
    ]
