# Generated by Django 4.2 on 2025-05-04 06:34

import course.enrollment.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("chapter", "0001_initial"),
        ("course", "0001_initial"),
        ("student_user", "0001_initial"),
        ("enrollment", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseChapterEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapter_enrollments",
                        to="chapter.chapter",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapter_enrollments",
                        to="course.course",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=models.SET(
                            course.enrollment.models.get_dummy_student
                        ),
                        related_name="chapter_enrollments",
                        to="student_user.student",
                    ),
                ),
            ],
            options={
                "db_table": "course_chapter_enrollment",
                "unique_together": {("student", "course", "chapter")},
            },
        ),
    ]
