# Generated by Django 4.2 on 2025-04-04 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="language",
            field=models.CharField(
                choices=[("en", "En"), ("pl", "Pl")], default="pl", max_length=2
            ),
            preserve_default=False,
        ),
    ]
