apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: default
  annotations:
    app.kubernetes.io/managed-by: "Helm"
data:
  LOCAL: "False"
  ENV: {{ .Values.env.ENV }}
  CSRF_TRUSTED_ORIGINS: {{ .Values.env.CSRF_TRUSTED_ORIGINS }}
  ALLOWED_HOST: {{ .Values.env.ALLOWED_HOST }}
  MIN_PASSWORD_LENGTH: "8"
  DB_NAME: "postgres"
  DB_HOST: "postgresql"
  DB_PORT: "5432"
  BROKER_URL: "http://broker:4000"
