apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: default
  annotations:
    app.kubernetes.io/managed-by: "Helm"
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
