name: Continuous Deployment

on:
  push:
    branches: [develop]

jobs:
  lint-backend:
    uses: ./.github/workflows/linting/backend.yml
    needs: detect-changes

  lint-broker:
    uses: ./.github/workflows/linting/broker.yml
    needs: detect-changes

  lint-frontend:
    uses: ./.github/workflows/linting/frontend.yml
    needs: detect-changes

  lint-python-sandbox:
    uses: ./.github/workflows/linting/sandbox/python.yml
    needs: detect-changes

  test-backend:
    uses: ./.github/workflows/testing/backend.yml
    needs: lint-backend

  test-broker:
    uses: ./.github/workflows/testing/broker.yml
    needs: lint-broker

  test-frontend:
    uses: ./.github/workflows/testing/frontend.yml
    needs: lint-frontend

  test-python-sandbox:
    uses: ./.github/workflows/testing/sandbox/python.yml
    needs: lint-python-sandbox

  build-and-push-backend:
    uses: ./.github/workflows/building/build.yml
    needs: test-backend
    with:
      service: backend
      context: ./backend
      image_name: loopedupl/backend
      tag: ${{ github.run_id }}.dev

  build-and-push-broker:
    uses: ./.github/workflows/building/build.yml
    needs: test-broker
    with:
      service: broker
      context: ./broker
      image_name: loopedupl/broker
      tag: ${{ github.run_id }}.dev

  build-and-push-frontend:
    uses: ./.github/workflows/building/build.yml
    needs: test-frontend
    with:
      service: frontend
      context: ./frontend
      image_name: loopedupl/frontend
      tag: ${{ github.run_id }}.dev

  build-and-push-python-sandbox:
    uses: ./.github/workflows/building/build.yml
    needs: test-python-sandbox
    with:
      service: python sandbox
      context: ./sandbox/python
      image_name: loopedupl/python-sandbox
      tag: ${{ github.run_id }}.dev

  build-and-push-nginx:
    uses: ./.github/workflows/building/build.yml
    needs:
      [
        build-and-push-backend,
        build-and-push-broker,
        build-and-push-frontend,
        build-and-push-python-sandbox,
      ]
    with:
      service: nginx
      context: ./nginx
      image_name: loopedupl/nginx
      tag: ${{ github.run_id }}.dev

  deploy-to-dev:
    uses: ./.github/workflows/deployment/deploy.yml
    needs: build-and-push-nginx
    with:
      environment: dev
      kube_config_secret: ${{ secrets.KUBE_CONFIG_DEV }}
      tag_value: ${{ github.run_id }}.dev
