name: Continuous Improvement

on:
  pull_request:
    branches: [develop]

jobs:
  detect-changes:
    uses: ./.github/workflows/detect.yml
    with:
      token: ${{ secrets.PAT_FOR_FILTER }}

  lint-backend:
    uses: ./.github/workflows/lint-backend.yml
    needs: detect-changes
    if: needs.detect-changes.outputs.backend == 'true'

  lint-broker:
    uses: ./.github/workflows/lint-broker.yml
    needs: detect-changes
    if: needs.detect-changes.outputs.broker == 'true'

  lint-frontend:
    uses: ./.github/workflows/lint-frontend.yml
    needs: detect-changes
    if: needs.detect-changes.outputs.frontend == 'true'

  lint-python-sandbox:
    uses: ./.github/workflows/lint-sandbox-python.yml
    needs: detect-changes
    if: needs.detect-changes.outputs.sandbox-python == 'true'

  test-backend:
    uses: ./.github/workflows/test-backend.yml
    needs: lint-backend
    if: needs.detect-changes.outputs.backend == 'true'
    with:
      LOCAL: ${{ secrets.LOCAL }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      REDIS_URL: ${{ secrets.REDIS_URL }}
      CONTACT_EMAIL: ${{ secrets.CONTACT_EMAIL }}
      NOREPLY_EMAIL: ${{ secrets.NOREPLY_EMAIL }}
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
      ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
      DUMMY_STUDENT_EMAIL: ${{ secrets.DUMMY_STUDENT_EMAIL }}
      DUMMY_STUDENT_PASSWORD: ${{ secrets.DUMMY_STUDENT_PASSWORD }}

  test-broker:
    uses: ./.github/workflows/test-broker.yml
    needs: lint-broker
    if: needs.detect-changes.outputs.broker == 'true'

  test-frontend:
    uses: ./.github/workflows/test-frontend.yml
    needs: lint-frontend
    if: needs.detect-changes.outputs.frontend == 'true'

  test-python-sandbox:
    uses: ./.github/workflows/test-sandbox-python.yml
    needs: lint-python-sandbox
    if: needs.detect-changes.outputs.sandbox-python == 'true'
