name: Continuous Improvement

on:
  pull_request:
    branches: [develop]

jobs:
  detect-changes:
    uses: ./.github/workflows/detecting/detect.yml
    secrets:
      token: ${{ secrets.PAT_FOR_FILTER }}
