name: Detect Changes Workflow

on:
  workflow_call:
    inputs:
      token:
        required: true
        type: string

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
      broker: ${{ steps.filter.outputs.broker }}
      sandbox-python: ${{ steps.filter.outputs.sandbox-python }}
    steps:
      - name: Detect changes using paths-filter
        uses: dorny/paths-filter@v3
        id: filter
        with:
          token: ${{ inputs.token }}
          filters: |
            backend:
              - 'backend/**'
            frontend:
              - 'frontend/**'
            broker:
              - 'broker/**'
            sandbox-python:
              - 'sandbox/python/**'
