name: Deployment on release

on:
  push:
    tags:
      - v*.*.*
  workflow_dispatch:

jobs:
  lint-backend:
    uses: ./.github/workflows/lint-backend.yml

  lint-broker:
    uses: ./.github/workflows/lint-broker.yml

  lint-frontend:
    uses: ./.github/workflows/lint-frontend.yml

  lint-python-sandbox:
    uses: ./.github/workflows/lint-sandbox-python.yml

  lint-ai-sandbox:
    uses: ./.github/workflows/lint-sandbox-ai.yml

  test-backend:
    uses: ./.github/workflows/test-backend.yml
    needs: lint-backend
    secrets:
      LOCAL: ${{ secrets.LOCAL }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_HOST: ${{ secrets.DB_HOST }}
      REDIS_URL: ${{ secrets.REDIS_URL }}
      CONTACT_EMAIL: ${{ secrets.CONTACT_EMAIL }}
      NOREPLY_EMAIL: ${{ secrets.NOREPLY_EMAIL }}
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
      ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
      DUMMY_STUDENT_EMAIL: ${{ secrets.DUMMY_STUDENT_EMAIL }}
      DUMMY_STUDENT_PASSWORD: ${{ secrets.DUMMY_STUDENT_PASSWORD }}

  test-broker:
    uses: ./.github/workflows/test-broker.yml
    needs: lint-broker

  test-frontend:
    uses: ./.github/workflows/test-frontend.yml
    needs: lint-frontend

  test-python-sandbox:
    uses: ./.github/workflows/test-sandbox-python.yml
    needs: lint-python-sandbox

  test-ai-sandbox:
    uses: ./.github/workflows/test-sandbox-ai.yml
    needs: lint-ai-sandbox

  build-and-push-backend-dev:
    uses: ./.github/workflows/build.yml
    needs: test-backend
    with:
      service: backend
      context: ./backend
      image_name: loopedupl/backend
      tag: ${{ github.run_id }}.dev
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}

  build-and-push-broker-dev:
    uses: ./.github/workflows/build.yml
    needs: test-broker
    with:
      service: broker
      context: ./broker
      image_name: loopedupl/broker
      tag: ${{ github.run_id }}.dev
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}

  build-and-push-frontend-dev:
    uses: ./.github/workflows/build.yml
    needs: test-frontend
    with:
      service: frontend
      context: ./frontend
      image_name: loopedupl/frontend
      tag: ${{ github.run_id }}.dev
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}

  build-and-push-python-sandbox-dev:
    uses: ./.github/workflows/build.yml
    needs: test-python-sandbox
    with:
      service: python-sandbox
      context: ./sandbox/python
      image_name: loopedupl/python-sandbox
      tag: ${{ github.run_id }}.dev
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}

  build-and-push-ai-sandbox-dev:
    uses: ./.github/workflows/build.yml
    needs: test-ai-sandbox
    with:
      service: ai-sandbox
      context: ./sandbox/ai
      image_name: loopedupl/ai-sandbox
      tag: ${{ github.run_id }}.dev
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}

  build-and-push-nginx-dev:
    uses: ./.github/workflows/build.yml
    needs:
      [
        build-and-push-backend-dev,
        build-and-push-broker-dev,
        build-and-push-frontend-dev,
        build-and-push-python-sandbox-dev,
        build-and-push-ai-sandbox-dev,
      ]
    with:
      service: nginx
      context: ./nginx
      image_name: loopedupl/nginx
      tag: ${{ github.run_id }}.dev
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}

  deploy-to-dev:
    uses: ./.github/workflows/deploy.yml
    needs: build-and-push-nginx-dev
    with:
      environment: dev
      tag_value: ${{ github.run_id }}.dev
    secrets:
      kube_config_data: ${{ secrets.KUBE_CONFIG_DEV }}

  build-and-push-broker-prod:
    uses: ./.github/workflows/build.yml
    needs: deploy-to-dev
    with:
      service: broker
      context: ./broker
      image_name: loopedupl/broker
      tag: ${{ github.run_id }}.prod
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}

  build-and-push-frontend-prod:
    uses: ./.github/workflows/build.yml
    needs: deploy-to-dev
    with:
      service: frontend
      context: ./frontend
      image_name: loopedupl/frontend
      tag: ${{ github.run_id }}.prod
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}

  build-and-push-python-sandbox-prod:
    uses: ./.github/workflows/build.yml
    needs: deploy-to-dev
    with:
      service: python-sandbox
      context: ./sandbox/python
      image_name: loopedupl/python-sandbox
      tag: ${{ github.run_id }}.prod
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}

  build-and-push-ai-sandbox-prod:
    uses: ./.github/workflows/build.yml
    needs: deploy-to-dev
    with:
      service: ai-sandbox
      context: ./sandbox/ai
      image_name: loopedupl/ai-sandbox
      tag: ${{ github.run_id }}.prod
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}

  build-and-push-nginx-prod:
    uses: ./.github/workflows/build.yml
    needs:
      [
        build-and-push-backend-prod,
        build-and-push-broker-prod,
        build-and-push-frontend-prod,
        build-and-push-python-sandbox-prod,
        build-and-push-ai-sandbox-prod,
      ]
    with:
      service: nginx
      context: ./nginx
      image_name: loopedupl/nginx
      tag: ${{ github.run_id }}.prod
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}

  deploy-to-prod:
    uses: ./.github/workflows/deploy.yml
    needs: build-and-push-nginx-prod
    with:
      environment: prod
      tag_value: ${{ github.run_id }}.prod
    secrets:
      kube_config_data: ${{ secrets.KUBE_CONFIG_PROD }}
