name: Backend Testing Workflow

on:
  workflow_call:
    inputs:
      LOCAL:
        required: true
        type: string
      DB_NAME:
        required: true
        type: string
      DB_HOST:
        required: true
        type: string
      DB_USER:
        required: true
        type: string
      DB_PASSWORD:
        required: true
        type: string
      REDIS_URL:
        required: true
        type: string
      CONTACT_EMAIL:
        required: true
        type: string
      NOREPLY_EMAIL:
        required: true
        type: string
      GOOGLE_CREDENTIALS:
        required: true
        type: string
      ADMIN_EMAIL:
        required: true
        type: string
      ADMIN_PASSWORD:
        required: true
        type: string
      DUMMY_STUDENT_EMAIL:
        required: true
        type: string
      DUMMY_STUDENT_PASSWORD:
        required: true
        type: string

jobs:
  test-backend:
    name: Test Backend
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:7.2.5-bookworm
        ports: [6379:6379]
        options: --health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 5
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports: [5432:5432]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        env:
          LOCAL: ${{ inputs.LOCAL }}
          DB_NAME: ${{ inputs.DB_NAME }}
          DB_HOST: ${{ inputs.DB_HOST }}
          DB_USER: ${{ inputs.DB_USER }}
          DB_PASSWORD: ${{ inputs.DB_PASSWORD }}
          REDIS_URL: ${{ inputs.REDIS_URL }}
          CONTACT_EMAIL: ${{ inputs.CONTACT_EMAIL }}
          NOREPLY_EMAIL: ${{ inputs.NOREPLY_EMAIL }}
          GOOGLE_CREDENTIALS: ${{ inputs.GOOGLE_CREDENTIALS }}
          ADMIN_EMAIL: ${{ inputs.ADMIN_EMAIL }}
          ADMIN_PASSWORD: ${{ inputs.ADMIN_PASSWORD }}
          DUMMY_STUDENT_EMAIL: ${{ inputs.DUMMY_STUDENT_EMAIL }}
          DUMMY_STUDENT_PASSWORD: ${{ inputs.DUMMY_STUDENT_PASSWORD }}
        run: |
          cd backend
          sudo apt-get install -y libjpeg-dev
          python -m pip install --upgrade pip
          pip install -r requirements-test.txt
          pip install -r requirements.txt
          pip install django-cors-headers

      - name: Run tests
        run: |
          coverage run manage.py test
          coverage report
